### ISSUE TITLE
restart.vim で作成される Session ファイルの保存場所・削除のタイミングを考える

### ISSUE THREAD

**Issue by osyo-manga** [tyru/restart.vim#12]
以前、ものすごくはまったので対応するかどうかは置いておいて issues に書いておきます。

さて、Session ファイルはリスタート時にカレントディレクトリに一時的に作成され、その後削除されます。
この Session ファイルなのですが、`:Restart` コマンドの引数を色々と試している時にコマンド引数がよろしくなかったためか Session ファイルが削除されずにそのまま残っている事がありました。
この時に Session ファイルが `runtimepath` の `plugin` に作成されて残ったままになってしまい Vim を起動するたびに Session ファイルが読み込まれてすごく混乱してしまいました。
これを回避するための対策としては以下のようなものが考えられます。

- Session ファイルの作成場所を変更する
 - 例えば `tempname()` とか
- Session ファイルの削除のタイミングを変更する
 - 起動する Vim ではなくて起動中の Vim で削除したほうが安全？

と、いう感じでレアなケースではありますが、絶対にないとは言い切れないので一応 issues に書いておきます。

**Comment by tyru** [comment]
ものすごく遅くなりましたが、とりあえず`tempname()`を使う案でやってみました。
もうカレントディレクトリにセッションファイルが作成されたままになることはなくなったはずです。

**Comment by osyo-manga** [comment]
ありがとうございます。

**Comment by thinca** [comment]
FYI: Linux では、`tempname()` は Vim のインスタンス毎に `/tmp/vXXXXXX`(`XXXXXX` はランダムな英数字) と言うディレクトリを生成し、このディレクトリ内の連番(`/tmp/vXXXXXX/1` のような)を名前として返します。この `/tmp/vXXXXXX` ディレクトリは、Vim の終了時に中身も含めて削除されます。

**Comment by tyru** [comment]
あーなるほど…Linuxでしたか。
ありがとうございます。

**Comment by tyru** [comment]
ん？そういえばWindows以外は
新しいVimの起動を待って現在のVim終了するので問題ない気がしてきました。
（WindowsはVim起動にstartコマンドを使うので新しいVimが起動し切ってsession fileを参照するまで待たず現在のVimが終了される場合がある）
調査するのでとりあえずopenで。

**Comment by tyru** [comment]
調査の結果、Vimが起動しきるまで待たないといけない事が判明したので、修正しました…
LinuxとWindowsで動作確認済みです。

@thinca 情報ありがとうございました！
