### ISSUE TITLE
cmd + ctrl + f などのショートカットキーが効かなくなる

### ISSUE THREAD

**Issue by basyura** [tyru/restart.vim#17]
# 環境

    MacVim-kaoriya
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 31 2014 10:36:38)
    MacOS X (unix) 版
    適用済パッチ: 1-383

# gvim 起動時にエラーがでる

    /Applications/MacVim.app/Contents/Resources/vim/runtime/menu.vim の処理中にエラーが検出されました:
    行 1189:
    E334: メニューが見つかりません: File.New\ Window    

エラーが出ている箇所

- menu.vim

````
    if has("gui_macvim")
      "
      " Set up menu key equivalents (these should always have the 'D' modifier
      " set), action bindings, and alternate items.
      "
      " Note: menu items which should execute an action are bound to <Nop>; the
      " action message is specified here via the :macmenu command.
      "
      macm File.New\ Window				key=<D-n> action=newWindow:
      macm File.New\ Tab				key=<D-t>
      macm File.Open\.\.\.				key=<D-o> action=fileOpen:
      nmacm File.Open\ Tab\.\.\.<Tab>:tabnew		key=<D-T>
      macm File.Open\ Recent			action=recentFilesDummy:
````

# 発生要因

- plugin/restart.vim

````
  " Menu {{{
  if !get(g:, 'restart_no_default_menus', 0)
      if get(g:, 'restart_menu_lang', &langmenu !=# '' ? &langmenu : v:lang) ==# 'ja'
          execute "nnoremenu <silent> 10.601 File.再起動(&R)<Tab>:Restart :" . g:restart_command . '<CR>'
      else
          execute "nnoremenu <silent> 10.601 File.&Restart<Tab>:Restart :" . g:restart_command . '<CR>'
      endif
      nnoremenu 10.602 File.-RestartSep- :
  endif
````

このときの &langmenu は `ja_ja.utf-8.macvim ` なので else に入るけど
メニュー設定がうまくいっていない模様

![2014-09-18 13 24 51](https://cloud.githubusercontent.com/assets/42623/4315588/8b5fe120-3ef8-11e4-8688-659a184fa94d.png)

# 対応

方法まで調べきれてません・・・`g:restart_no_default_menus=1` にすれば回避できますレベル・・・。

気になるのは、デフォルトでメニュー設定が意図通りにいってなかった場合にハマってしまう人が出そうなところですかね・・・。

**Comment by tyru** [comment]
これって今でも再現するでしょうか？

**Comment by basyura** [comment]
もう再現しなくなって困っていないので閉じてしまいますね

**Comment by tyru** [comment]
了解です。ありがとうございました。
