### ISSUE TITLE
Windows: Vim 7.4 (32bit) causes SegFault when calling libcallnr('User32.dll', 'IsZoomed', v:windowid)

### ISSUE THREAD

**Issue by Jagua** [tyru/restart.vim#18]
I want the switch to omit s:check_window_maximized().

**Comment by tyru** [comment]
Added g:restart_check_window_maximized option.
Please write the following setting to your vimrc.

    let g:restart_check_window_maximized = 0

**Comment by Jagua** [comment]
It works fine on Vim 7.4 (32bit). Thanks!
